name: Restful Booker CI

on:
  workflow_call:  # Make it a reusable workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: Restful Booker # Check out into the project directory

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd Restful Booker
          npm install

      - name: Run Playwright install
        run: |
          cd Restful Booker
          npx playwright install --with-deps

      - name: Run tests
        run: |
          cd Restful Booker
          npx playwright test

      - name: Generate Playwright report
        run: |
          cd Restful Booker
          npx playwright show-report

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report-restful-booker
          path: Restful Booker/playwright-report/
          retention-days: 30