name: Sauce Demo CI

on:
  workflow_call:  # Make it a reusable workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: Sauce Demo # Check out into the project directory

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd Sauce Demo
          npm install

      - name: Run Playwright install
        run: |
          cd Sauce Demo
          npx playwright install --with-deps

      - name: Run tests
        run: |
          cd Sauce Demo
          npx playwright test

      - name: Generate Playwright report
        run: |
          cd Sauce Demo
          npx playwright show-report

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report-sauce-demo
          path: Sauce Demo/playwright-report/
          retention-days: 30