name: Multi-Project CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      project:
        description: 'Project to run'
        required: true
        type: choice
        options:
          - restful-booker
          - sauce-demo

jobs:
  run-restful-booker-tests:
    if: github.event_name == 'push' || github.event.inputs.project == 'restful-booker'
    uses: ./.github/workflows/restful-booker.yml

  run-sauce-demo-tests:
    if: github.event_name == 'push' || github.event.inputs.project == 'sauce-demo'
    uses: ./.github/workflows/sauce-demo.yml